# Generated by Django 3.0.6 on 2020-05-21 23:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='best',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='worst',
            new_name='illustrator',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review',
        ),
        migrations.AddField(
            model_name='review',
            name='comments',
            field=models.TextField(default='Blank', max_length=1500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='exciting',
            field=models.TextField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='funniest',
            field=models.TextField(default='Blank', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='happiest',
            field=models.TextField(default='Blank', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='saddest',
            field=models.TextField(default='Blank', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.TextField(default='Blank', max_length=200),
            preserve_default=False,
        ),
    ]
